### ISSUE TITLE
 feature request

### ISSUE THREAD

**Issue by fortunejuggle** [netmanagers/salt-image-builder#10]
I would like to test `ubuntu,16.04,2019.2,stable,3`

is it possible to bring this to `upstream's images` ? 

Thanks and Regards

**Comment by javierbertoli** [comment]
Hi @fortunejuggle. Yes, I can add it, no problem. However, current `2019.2` (2019.2.1) is seriously broken (jinja2 parsing issues, etc.) and I'm waiting for 2019.2.2 to be released sometime this/next week. Are you OK with waiting a little?

**Comment by fortunejuggle** [comment]
Hi @javierbertoli - it was quick - Iam aware of the completely broken 2019.2.1 version, of course I wait. Thanks
