### ISSUE TITLE
Add support for AmazonLinux/python3

### ISSUE THREAD

**Issue by javierbertoli** [netmanagers/salt-image-builder#16]
It seems it can be installed using packages, so we should try to see if either the bootstrap supports it, or we should add the repo directly.

**Comment by myii** [comment]
Some references:

* https://repo.saltstack.com/#amzn
* https://repo.saltstack.com/py3/amazon/2/x86_64/latest/

**Comment by stanabs-mgt** [comment]
hi sir, how are you? tarik here. could you plz help me learn like you?
