### ISSUE TITLE
Provide image for Gentoo

### ISSUE THREAD

**Issue by myii** [netmanagers/salt-image-builder#19]
Was looking at:

* https://github.com/saltstack-formulas/php-formula/pull/205

Which itself was based on:

* https://github.com/saltstack-formulas/php-formula/pull/156 (merged by @javierbertoli!)

Tried to get a Gentoo docker image running but it is a very difficult proposition.  Unless I'm missing something, there's no way this is going to be achieved as part of the Travis matrix, the build takes _forever_.

However, if we can prepare a pre-salted image manually, could we just maintain and upload this separately?

**Comment by myii** [comment]
Brief notes about what I tried:

https://hub.docker.com/u/gentoo

* Started with the official images but these need configuration before they're going to work
  - `gentoo/stage3-x86` -- fails when running `emerge`
  - `gentoo/portage` -- `emerge` not available

https://hub.docker.com/r/mesaguy

* Found more useful images here [using this search](https://github.com/search?l=YAML&p=1&q=gentoo+kitchen&type=Code), linked to Ansible usage
  - https://github.com/mesaguy/docker/blob/c08f4213826b673b92b0459ee277322572cbda3f/kitchen-ansible-x86_64/kitchen.yml#L370-L385
  - `gentoo-systemd-boot-x86_64` -- used this one, with some configuration
  - `gentoo-openrc-boot-x86_64`

https://packages.gentoo.org/packages/app-admin/salt

* This is the package installed by the bootstrap
* Problem is that is still in testing, so can't be installed as-is without allowing test packages
* Error: `All ebuilds that could satisfy have been masked. (masked by: ~amd64 keyword)`

https://chromium.googlesource.com/chromiumos/docs/+/master/portage/ebuild_faq.md#the-package-i-want-to-install-has-been-masked_how-do-i-fix-that

* Found the solution here, i.e.
  - `echo 'ACCEPT_KEYWORDS="~amd64"' | tee -a /etc/portage/make.conf`

**Comment by javierbertoli** [comment]
Using saltbootstrap fails, the reason is a required package [was retired by gentoo](https://github.com/saltstack/salt/issues/52725#issuecomment-487692322)

**Comment by myii** [comment]
> Using saltbootstrap fails, the reason is a required package [was retired by gentoo](https://github.com/saltstack/salt/issues/52725#issuecomment-487692322)

@javierbertoli Ah yes, I could have mentioned that as well.  That only affects `git` installations, not `stable`.

**Comment by javierbertoli** [comment]
yes, I submit that while building the stable version. I'll see if I upload those images these days,I need to check how to get the desired salt version built/installed

**Comment by mgomersbach** [comment]
> Brief notes about what I tried:
> 
> https://hub.docker.com/u/gentoo
> 
>     * Started with the official images but these need configuration before they're going to work
>       
>       * `gentoo/stage3-x86` -- fails when running `emerge`
>       * `gentoo/portage` -- `emerge` not available
> 

Stage 3 and portage snapshot work together.
Stage 3 is the gentoo base userland, portage here is the repository with package information (ebuilds) .
Stage 3 has a package manager "emerge" that calls a python library "portage" which resolves information in the portage snapshot.
You'll want stage3-amd64 while you are it.

> 
> https://hub.docker.com/r/mesaguy
> 
>     * Found more useful images here [using this search](https://github.com/search?l=YAML&p=1&q=gentoo+kitchen&type=Code), linked to Ansible usage
>       
>       * https://github.com/mesaguy/docker/blob/c08f4213826b673b92b0459ee277322572cbda3f/kitchen-ansible-x86_64/kitchen.yml#L370-L385
>       * `gentoo-systemd-boot-x86_64` -- used this one, with some configuration
>       * `gentoo-openrc-boot-x86_64`
> 

Can't really say how up to date that is, but using images from [Kubler](https://github.com/edannenberg/kubler) might seem similar.
Then again, I would just start a new dockerfile based on the upstream images from Gentoo. Add a package cache so you are not compiling the same system packages over and over again would be advised. You want to test Saltstack, not Gentoo :)

> 
> https://packages.gentoo.org/packages/app-admin/salt
> 
>     * This is the package installed by the bootstrap
> 
>     * Problem is that is still in testing, so can't be installed as-is without allowing test packages
> 
>     * Error: `All ebuilds that could satisfy have been masked. (masked by: ~amd64 keyword)`
> 
> 
> https://chromium.googlesource.com/chromiumos/docs/+/master/portage/ebuild_faq.md#the-package-i-want-to-install-has-been-masked_how-do-i-fix-that
> 
>     * Found the solution here, i.e.
>       
>       * `echo 'ACCEPT_KEYWORDS="~amd64"' | tee -a /etc/portage/make.conf`

Yeah, common pitfall, and a logical one too, however, from now entire "world" (all system packages + your installed packages) will now use the unstable branch (amd64 == stable / ~amd64 == unstable) and force an awful lot of rebuilds, if the package manager even is able to resolve it.

**Comment by myii** [comment]
@mgomersbach This is why we needed you here!  Real-life Gentoo experience is invaluable.

> You'll want stage3-amd64 while you are it.

Thanks, I missed that when looking down that list:

* https://hub.docker.com/r/gentoo/stage3-amd64

> Can't really say how up to date that is, but using images from [Kubler](https://github.com/edannenberg/kubler) might seem similar.
> Then again, I would just start a new dockerfile based on the upstream images from Gentoo. Add a package cache so you are not compiling the same system packages over and over again would be advised. You want to test Saltstack, not Gentoo :)

Yes, something like this would have been the long-term goal (after getting an initial image running).  You've given us a definition of that something, so that's great feedback.

> Yeah, common pitfall, and a logical one too, however, from now entire "world" (all system packages + your installed packages) will now use the unstable branch (amd64 == stable / ~amd64 == unstable) and force an awful lot of rebuilds, if the package manager even is able to resolve it.

Right, so what's the best way around this issue?  The alternative that I'm aware of is to enable testing packages for only `app-admin/salt`, something like:

* https://wiki.gentoo.org/wiki/Knowledge_Base:Accepting_a_keyword_for_a_single_package

Or:

* https://wiki.gentoo.org/wiki/Knowledge_Base:Unmasking_a_package

---

> yes, I submit that while building the stable version. I'll see if I upload those images these days,I need to check how to get the desired salt version built/installed

@mgomersbach What's the best way to install specific Salt versions?  It looks like `salt-bootstrap` needs to be improved to allow this.

**Comment by mgomersbach** [comment]
I am not sure, because I have not looked into this codebase yet. However, did fork it last night, so I'll hope to work on it tonight.

If you want as specific version of salt you could (leaving out arguments for brevity):
```sh
emerge "=app-admin/salt-2019.2.2"
```

Or if you want a specific feature compile with salt:
```sh
echo "app-admin/salt libvirt" >> /etc/portaga/package.use/app-admin/salt
```

Anyway, back to the Gentoo image:
During normal day usage you'll try to avoid using the next arguments:
```sh
emerge --autounmask --autounmask-continue=y --autounmask-use=y --autounmask-write=y app-admin/salt
```
Now the overrides _only_needed_for_salt_ are applied on the system, instead of unstable for the whole system. Much better.

But since this is only done to get Salt into place, it should be fine.
Saltstack itself has a nicer way of doing these things; Put all unmask/mask in separate files based on package names, as opposed to Gentoo, which just dump it in the last alphabetical file available in /etc/portage/package.* (being keywords, useflags or environments)

**Comment by myii** [comment]
Thanks @mgomersbach, this will be very helpful.
