### ISSUE TITLE
Showstopper bug in 2019.2.1

### ISSUE THREAD

**Issue by dafyddj** [netmanagers/salt-image-builder#7]
I don't know if these images are automatically rebuilt on a schedule but there is a showstopper bug in `2019.2.1` which will cause formula tests to fail when running against the latest version of Salt, (see saltstack/salt#54765) and I feel it may be best not to roll out that version.

**Comment by javierbertoli** [comment]
Hi @dafyddj. No, no automatic rebuild yet, so we're good to skip 2019.2.1. Also, there was a mention on the #releases channel that 2019.2.3 will probably be released next week, son let's see how things go there

**Comment by dafyddj** [comment]
Thanks. A fix has been proposed so fingers crossed that makes it into the next release.

I wonder what happened to 2019.2.2 though?

**Comment by dafyddj** [comment]
2019.2.2 has been released, fixing the Jinja import bug.
